name: Master CICD Pipeline

on:
  push:
    branches: [main]

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build . -t ghcr.io/$repo/edu-project-api:$git_hash

    - name: Test image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker run \
          --entrypoint=/bin/bash \
          ghcr.io/$repo/edu-project-api:$git_hash \
          ./script/test

    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$repo/edu-project-api:$git_hash